# refresh conf file 
unbind r 
bind-key r source ~/.tmux.conf

# disable some defaults
set-option -g allow-rename off

# global binding for prefix key
unbind C-s
set-option -g prefix C-s
bind-key C-s send-prefix

# pane splitting
bind '\' split-window -h
bind - split-window -v
unbind '"'
unbind %

# moving tiles
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
