# refresh conf file 
unbind r 
bind-key r source ~/.tmux.conf

# disable some defaults
set-option -g allow-rename off

# global binding for prefix key
unbind C-s
set-option -g prefix C-s
bind-key C-s send-prefix

# pane splitting
bind '\' split-window -h
bind - split-window -v
unbind '"'
unbind %

# mouse movement
set -g mouse on

# moving tiles
unbind M-h
bind -n M-h select-pane -L
bind -n M-j select-pane -D
bind -n M-k select-pane -U
bind -n M-l select-pane -R
